### ISSUE TITLE
Bit Defender Flags exe

### ISSUE THREAD

**Issue by Seanny101** [Robert-K/company-of-wasd#1]
I cannot use the exe.
Bit Defender deletes it as soon as I try to move the file from the zip to a new folder.

I really wanted to use this.
For COH 2 in particular.
But I also wanted to use for Dawn of War Soul Storm too.

Could test your exe with Bit Defender please?

**Comment by Robert-K** [comment]
Unfortunately, I cannot do anything about it getting flagged. The executable comes bundled with some AutoHotkey binaries which unsurprisingly look rather suspicious (AutoHotkey can emulate input, manage processes & system settings etc..).
You could just install AutoHotkey on your system and run the .ahk directly or try converting it yourself.
You should also just be able to add an exception for the executable in BitDefender settings.

**Comment by Seanny101** [comment]
I already tried autohotkey directly using your ahk.
This is good for me.
Thanks.

Sent from Mail for Windows
