### ISSUE TITLE
VirusTotal detects Trojan

### ISSUE THREAD

**Issue by Famienn** [Robert-K/company-of-wasd#2]
False positive?

**Comment by Robert-K** [comment]
False positive. AutoHotKey is pretty mighty and usually triggers stuff.
If you want to be sure, you can run the script or compile it yourself :)

________________________________
From: Famienn ***@***.***>
Sent: Wednesday, 14 August 2024 20:40
To: Robert-K/company-of-wasd
Cc: Subscribed
Subject: [Robert-K/company-of-wasd] VirusTotal detects Trojan (Issue #2)

False positive?
